/**
 * PROTOTYPE — throwaway. Read `prototype-shell.ts` for the question this answers.
 *
 * The corpus, reduced to what a map can draw. `spec.md` says the map shows only what carries a
 * geometry, so this module is the one place that decides what "on the map" means, and every
 * variant reads it.
 *
 * It holds no state. It is computed once, at module load, from a fixture that never changes.
 */

import { corpus } from '@/shared/fixtures/corpus';
import type { Entity, Point } from '@/shared/fixtures/types';

/** One entity that carries a geometry, flattened for the renderer. */
export interface GeoEntity {
  /**
   * The MapLibre feature identifier. MapLibre wants a number or a string, and a number indexes
   * the lookup below with no cost. It is a position in this array and it is not the identity of
   * the entity — `id` is.
   */
  readonly fid: number;
  readonly id: string;
  readonly type: string;
  readonly label: string;
  readonly lon: number;
  readonly lat: number;
  readonly sourceIds: readonly string[];
}

/** `geom` is nullable on `Entity`, and the narrowing has to survive the `.map` below. */
const hasGeometry = (entity: Entity): entity is Entity & { readonly geom: Point } =>
  entity.geom !== null;

export const geoEntities: readonly GeoEntity[] = corpus.entities
  .filter(hasGeometry)
  .map((entity, index) => ({
    fid: index,
    id: entity.id,
    type: entity.type,
    label: entity.label,
    lon: entity.geom.lon,
    lat: entity.geom.lat,
    sourceIds: entity.sources,
  }));

export const byFid: ReadonlyMap<number, GeoEntity> = new Map(geoEntities.map((e) => [e.fid, e]));

/**
 * ADR 0005 §6: the panel is a projection of the type list, generated by the machine. Nobody
 * maintains this list by hand, and a type that no entity carries never appears. Sorted, so the
 * order of the fixture never reaches the screen.
 */
export const entityTypes: readonly string[] = [
  ...new Set(geoEntities.map((entity) => entity.type)),
].sort();

export function countOfType(type: string): number {
  return geoEntities.filter((entity) => entity.type === type).length;
}

/**
 * The six entity hues of `src/theme.css`, converted from `oklch` to hex.
 *
 * Two reasons for the copy. `theme.css` is imported by nothing yet, so `var(--entity-1)` would
 * resolve to nothing. And MapLibre parses a colour with its own parser, so a token would not
 * reach it in any case. The **dark** set is used, because every point sits on satellite imagery
 * and the light set is too dark to read on it. Rule 11 of the theme holds: these hues stay on
 * the map and never enter the chrome.
 */
const ENTITY_HUES = ['#70adfb', '#00c2d2', '#53c48e', '#a8b44b', '#df9b44', '#e887b6'] as const;

export function colourOfType(type: string): string {
  const hue = ENTITY_HUES[entityTypes.indexOf(type) % ENTITY_HUES.length];
  return hue ?? ENTITY_HUES[0];
}

/** Every point, so a variant can offer "show everything". */
export function boundsOfAll(): [number, number, number, number] {
  const lons = geoEntities.map((e) => e.lon);
  const lats = geoEntities.map((e) => e.lat);
  return [Math.min(...lons), Math.min(...lats), Math.max(...lons), Math.max(...lats)];
}
