/**
 * PROTOTYPE — throwaway. Read `prototype-shell.ts` for the question this answers.
 *
 * The corpus, reduced to what a map can draw. `spec.md` says the map shows only what carries a
 * geometry, so this module is the one place that decides what "on the map" means, and every
 * variant reads it.
 *
 * It holds no state. It is computed once, at module load, from a fixture that never changes.
 */

import { corpus } from '@/shared/fixtures/corpus';
import type { Attributes, Corpus, Entity, Point } from '@/shared/fixtures/types';

/** One entity that carries a geometry, flattened for the renderer. */
export interface GeoEntity {
  /**
   * The MapLibre feature identifier. MapLibre wants a number or a string, and a number indexes
   * the lookup below with no cost. It is a position in this array and it is not the identity of
   * the entity — `id` is.
   */
  readonly fid: number;
  readonly id: string;
  readonly type: string;
  readonly label: string;
  readonly lon: number;
  readonly lat: number;
  readonly sourceIds: readonly string[];
  /** M7 and M8: a value, and the documents that carry it. The rows read these. */
  readonly attrs: Attributes;
}

/** `geom` is nullable on `Entity`, and the narrowing has to survive the `.map` below. */
const hasGeometry = (entity: Entity): entity is Entity & { readonly geom: Point } =>
  entity.geom !== null;

export const geoEntities: readonly GeoEntity[] = corpus.entities
  .filter(hasGeometry)
  .map((entity, index) => ({
    fid: index,
    id: entity.id,
    type: entity.type,
    label: entity.label,
    lon: entity.geom.lon,
    lat: entity.geom.lat,
    sourceIds: entity.sources,
    attrs: entity.attrs,
  }));

export const byFid: ReadonlyMap<number, GeoEntity> = new Map(geoEntities.map((e) => [e.fid, e]));

/** Keyed by the identity of the entity, which is what the address of the route carries. */
export const byId: ReadonlyMap<string, GeoEntity> = new Map(geoEntities.map((e) => [e.id, e]));

/**
 * ADR 0005 §6: the panel is a projection of the type list, generated by the machine. Nobody
 * maintains this list by hand, and a type that no entity carries never appears. Sorted, so the
 * order of the fixture never reaches the screen.
 */
export const entityTypes: readonly string[] = [
  ...new Set(geoEntities.map((entity) => entity.type)),
].sort();

export function countOfType(type: string): number {
  return geoEntities.filter((entity) => entity.type === type).length;
}

/**
 * The six entity hues of `src/theme.css`, converted from `oklch` to hex.
 *
 * Two reasons for the copy. `theme.css` is imported by nothing yet, so `var(--entity-1)` would
 * resolve to nothing. And MapLibre parses a colour with its own parser, so a token would not
 * reach it in any case. The **dark** set is used, because every point sits on satellite imagery
 * and the light set is too dark to read on it. Rule 11 of the theme holds: these hues stay on
 * the map and never enter the chrome.
 */
const ENTITY_HUES = ['#70adfb', '#00c2d2', '#53c48e', '#a8b44b', '#df9b44', '#e887b6'] as const;

export function colourOfType(type: string): string {
  const hue = ENTITY_HUES[entityTypes.indexOf(type) % ENTITY_HUES.length];
  return hue ?? ENTITY_HUES[0];
}

/** Every point, so a variant can offer "show everything". */
/**
 * One relation whose **two** endpoints carry a geometry, so a line can be drawn for it.
 *
 * M4 permits a relation to point at another relation. Such a relation has no second point and
 * is not here — ADR 0004 §4 says the same of the graph, and it is reached through the detail
 * surface instead. `undrawableCount` counts what this list leaves out, because a map that
 * silently drops evidence is worse than one that says how much it dropped.
 */
export interface GeoLink {
  readonly fid: number;
  readonly id: string;
  readonly type: string;
  readonly from: GeoEntity;
  readonly to: GeoEntity;
  readonly sourceIds: readonly string[];
  readonly validFrom: string | null;
  readonly validTo: string | null;
  readonly attrs: Attributes;
}

const linkOf = (relation: Corpus['relations'][number], index: number): GeoLink | null => {
  if (relation.srcKind !== 'entity' || relation.dstKind !== 'entity') return null;
  const from = byId.get(relation.srcId);
  const to = byId.get(relation.dstId);
  if (from === undefined || to === undefined) return null;
  return {
    fid: index,
    id: relation.id,
    type: relation.type,
    from,
    to,
    sourceIds: relation.sources,
    validFrom: relation.validFrom,
    validTo: relation.validTo,
    attrs: relation.attrs,
  };
};

export const geoLinks: readonly GeoLink[] = corpus.relations
  .map(linkOf)
  .filter((link): link is GeoLink => link !== null);

export const undrawableCount = corpus.relations.length - geoLinks.length;

export const linkTypes: readonly string[] = [...new Set(geoLinks.map((link) => link.type))].sort();

export const byLinkFid: ReadonlyMap<number, GeoLink> = new Map(
  geoLinks.map((link) => [link.fid, link]),
);

/** Every drawn relation that touches this entity, in either direction. */
export function linksOf(entityId: string): GeoLink[] {
  return geoLinks.filter((link) => link.from.id === entityId || link.to.id === entityId);
}

export function boundsOfAll(): [number, number, number, number] {
  const lons = geoEntities.map((e) => e.lon);
  const lats = geoEntities.map((e) => e.lat);
  return [Math.min(...lons), Math.min(...lats), Math.max(...lons), Math.max(...lats)];
}
