/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as GraphRouteImport } from './routes/graph'
import { Route as MapRouteImport } from './routes/map'
import { Route as ReviewRouteImport } from './routes/review'
import { Route as EntityIdRouteImport } from './routes/entity.$id'
import { Route as ReviewDecidedRouteImport } from './routes/review_.decided'

const GraphRoute = GraphRouteImport.update({
  id: '/graph',
  path: '/graph',
  getParentRoute: () => rootRouteImport,
} as any)
const MapRoute = MapRouteImport.update({
  id: '/map',
  path: '/map',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewRoute = ReviewRouteImport.update({
  id: '/review',
  path: '/review',
  getParentRoute: () => rootRouteImport,
} as any)
const EntityIdRoute = EntityIdRouteImport.update({
  id: '/entity/$id',
  path: '/entity/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewDecidedRoute = ReviewDecidedRouteImport.update({
  id: '/review_/decided',
  path: '/review/decided',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/graph': typeof GraphRoute
  '/map': typeof MapRoute
  '/review': typeof ReviewRoute
  '/entity/$id': typeof EntityIdRoute
  '/review/decided': typeof ReviewDecidedRoute
}
export interface FileRoutesByTo {
  '/graph': typeof GraphRoute
  '/map': typeof MapRoute
  '/review': typeof ReviewRoute
  '/entity/$id': typeof EntityIdRoute
  '/review/decided': typeof ReviewDecidedRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/graph': typeof GraphRoute
  '/map': typeof MapRoute
  '/review': typeof ReviewRoute
  '/entity/$id': typeof EntityIdRoute
  '/review_/decided': typeof ReviewDecidedRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/graph' | '/map' | '/review' | '/entity/$id' | '/review/decided'
  fileRoutesByTo: FileRoutesByTo
  to: '/graph' | '/map' | '/review' | '/entity/$id' | '/review/decided'
  id:
    | '__root__'
    | '/graph'
    | '/map'
    | '/review'
    | '/entity/$id'
    | '/review_/decided'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  GraphRoute: typeof GraphRoute
  MapRoute: typeof MapRoute
  ReviewRoute: typeof ReviewRoute
  EntityIdRoute: typeof EntityIdRoute
  ReviewDecidedRoute: typeof ReviewDecidedRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/graph': {
      id: '/graph'
      path: '/graph'
      fullPath: '/graph'
      preLoaderRoute: typeof GraphRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/map': {
      id: '/map'
      path: '/map'
      fullPath: '/map'
      preLoaderRoute: typeof MapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/review': {
      id: '/review'
      path: '/review'
      fullPath: '/review'
      preLoaderRoute: typeof ReviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/entity/$id': {
      id: '/entity/$id'
      path: '/entity/$id'
      fullPath: '/entity/$id'
      preLoaderRoute: typeof EntityIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/review_/decided': {
      id: '/review_/decided'
      path: '/review/decided'
      fullPath: '/review/decided'
      preLoaderRoute: typeof ReviewDecidedRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  GraphRoute: GraphRoute,
  MapRoute: MapRoute,
  ReviewRoute: ReviewRoute,
  EntityIdRoute: EntityIdRoute,
  ReviewDecidedRoute: ReviewDecidedRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
